language: node_js
node_js:
 - "6"
 - "8"

before_install:
  - "mkdir cvc4/"
  - "wget https://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/cvc4-1.5-x86_64-linux-opt -O cvc4/cvc4"
  - chmod +x cvc4/cvc4
  - export PATH="`pwd`/cvc4:$PATH"
script:
  - yarn lint
  - yarn test
after_success: yarn run coverage
